- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    
    - name: Pause 1 min
      pause:
        minutes: 1

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
        owner: root

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

    - name: install Pod network
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    # - name: Install flannel
    #   shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.log"
    #   args:
    #     chdir: $HOME
    #     creates: pod_network_setup.log

    # - name: Downloading Kubernetes dashbaord
    #   get_url:
    #     url: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
    #     dest: /root/kubernetes-dashboard.yaml
    #     force: yes